version: 2.1
jobs:
  node:
    working_directory: ~/getting-started-example/packages/testApp
    docker:
      - image: cimg/node:16.20

    steps:
      - checkout
      - run: yarn install

  android-build-and-test:
    working_directory: ~/getting-started-example/packages/testApp/android
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout:
          path: ~/getting-started-example/packages/testApp

      - attach_workspace:
          at: ~/getting-started-example/packages/testApp
      
      - run:
          name: build android
          command: |
            ./gradlew clean
            ./gradlew assembleRelease
            mkdir -p out
            mv app/build/outputs/apk/release/app-release.apk ~/out/release.apk
      - store_artifacts:
          path: out


workflows:
  node-android-ios:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node