version: 2.1
jobs:
  node:
    # working_directory: ~/getting-started-example/packages/testApp
    docker:
      - image: cimg/node:16.20

    steps:
      - checkout
      - run: yarn install

  android-build-and-test:
    # working_directory: ~/getting-started-example/packages/testApp/android
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout:
          path: ~/project

      - attach_workspace:
          at: ~/project
      
      - run:
          name: build android
          command: |
            cd ~
            pwd
            echo "-------------"
            echo "PROJECT"
            ls -la project
            echo "-------------"
            echo "SRC"
            ls -la src
            echo "-------------"
            mkdir -p out
            pwd
            ls -la
            echo "-------------"
            echo "INSIDE PROJECT"
            cd project
            pwd
            ls -la
            echo "-------------"
            echo "INSIDE SRC"
            cd ../src
            pwd
            ls -la
            echo "-------------"
            cd packages/testApp/android
            ls -la
            ./gradlew clean
            ./gradlew assembleRelease
            mv app/build/outputs/apk/release/app-release.apk ${CIRCLE_WORKING_DIRECTORY}/out/release.apk
      - store_artifacts:
          path: ${CIRCLE_WORKING_DIRECTORY}/out


workflows:
  node-android-ios:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node