version: 2.1
jobs:
  node:
    working_directory: ./packages/testApp
    docker:
      - image: cimg/node:16.20

    steps:
      - checkout
      - run: yarn install

  android-build-and-test:
    working_directory: ./packages/testApp/android
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout:
          path: ./packages/testApp

      - attach_workspace:
          at: ./packages/testApp

workflows:
  node-android-ios:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node