version: 2.1
jobs:
  node:
    # working_directory: ~/getting-started-example/packages/testApp
    docker:
      - image: cimg/node:16.20

    steps:
      - checkout
      - run: yarn install
  
  sonarqube:
    docker:
      - image: sonarqube:latest
    steps:
      - run: |
          echo "---------"
          echo "INSTALLING SONAR-SCANNER"
          brew install sonar-scanner
          echo "---------"
          cd ~
          echo "---------"
          cd project
          echo "---------"
          cd packages
          echo "---------"
          pwd
          echo "---------"
          ls -la
          sonar-scanner \
            -Dsonar.projectKey=UFE \
            -Dsonar.sources=./testApp \
            -Dsonar.login=admin \
            -Dsonar.password=admin \
            -Dsonar.host.url=http://localhost:9000

  android-build-and-test:
    # working_directory: ~/getting-started-example/packages/testApp/android
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout:
          path: ~/project

      - attach_workspace:
          at: ~/project
      
      - run:
          name: build android
          command: |
            cd ~
            mkdir -p out
            cd project
            cd packages/testApp
            npm install
            cd android
            ./gradlew clean
            ./gradlew assembleRelease
            mv app/build/outputs/apk/release/app-release.apk ~/out/release.apk
      - store_artifacts:
          path: ~/out


workflows:
  node-android-ios:
    jobs:
      - node
      - sonarqube
      - android-build-and-test:
          requires:
            - node