version: 2.1
jobs:
  node:
    # working_directory: ~/getting-started-example/packages/testApp
    docker:
      - image: cimg/node:16.20

    steps:
      - checkout
      - run: yarn install
  
  # sonarqube:
  #   docker:
  #     - image: sonarqube:latest
  #   steps:
  #     - run: |
  build:
    macos:
      xcode: 14.2.0

    steps:
      - checkout:
            path: ~/project
      # Commands will execute in macOS container
      # with Xcode 14.2.0 installed
      - run: |
          echo "------BREW------"
          brew install sonar-scanner
          echo "------PWD------"
          pwd
          cd ~
          echo "------ LS ~ ------"
          ls -la
          cd project
          echo "------LS PROJECT------"
          ls -la
          echo "INSTALL DOCKER"
          set -x
          curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          echo "------DOCKER------"
          docker-compose up -d
          echo "------SONAR SCANNER------"
          sonar-scanner \
            -Dsonar.projectKey=UFE \
            -Dsonar.sources=./src \
            -Dsonar.login=admin \
            -Dsonar.password=admin \
            -Dsonar.host.url=http://localhost:9000
          echo "------DONE!------"


  android-build-and-test:
    # working_directory: ~/getting-started-example/packages/testApp/android
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout:
          path: ~/project

      - attach_workspace:
          at: ~/project
      
      - run:
          name: build android
          command: |
            cd ~
            mkdir -p out
            cd project
            cd packages/testApp
            npm install
            cd android
            ./gradlew clean
            ./gradlew assembleRelease
            mv app/build/outputs/apk/release/app-release.apk ~/out/release.apk
      - store_artifacts:
          path: ~/out


workflows:
  node-android-ios:
    jobs:
      - node
      - build
      - android-build-and-test:
          requires:
            - node